// priority: 21
REIEvents.hide('item', event => {
    event.hide([

        // Minecraft
        'minecraft:barrier',
        'minecraft:jigsaw',
        'minecraft:light',
        'minecraft:structure_block',
        'minecraft:structure_void',
        'minecraft:shield',
        'minecraft:bundle',
        'minecraft:tipped_arrow',


        //Dynamic Trees
        'dynamictrees:dendro_potion',
        'dynamictrees:dead_branch',

        //Origins
        'origins:orb_of_origin',

        //Comforts
        '/:.*hammock/',
        'comforts:rope_and_nail',


        //MC DOOM

        'doom:inmortalsphere',
        'doom:megasphere',
        'doom:darklord_boots',
        'doom:darklord_leggings',
        'doom:darklord_chestplate',
        'doom:darklord_helmet',
        '/:.*doom_helmet/',
        '/:.*doom_boots/',
        '/:.*doom_chestplate/',
        '/:.*doom_leggings/',
        'doom:twenty_five_helmet',
        'doom:twenty_five_chestplate',
        'doom:twenty_five_leggings',
        'doom:twenty_five_boots',
        'doom:classic_red_chestplate',
        'doom:classic_red_leggings',
        '/:.*classic_black/',
        '/:.*classic_bronze/',
        '/:.*redneck_doom/',
        '/:.*hotrod/',
        '/:.*santa_helmet/',
        'doom:soulcube',

        //Vinery
        'vinery:straw_hat',
        'vinery:vinemaker_apron',
        'vinery:vinemaker_leggings',
        'vinery:vinemaker_boots',

        //Gothic

        '/:.*magic_ore_armor/',
        '/:.*guru_armor/',
        '/:.*ravens_guard/',
        '/:.*citizen_armor/',
        '/:.*peasant_armor/',
        '/:.*crawler_armor/',
        '/:.*miner_leggings/',
        '/:.*guardian_armor/',
        '/:.*ghost_armor/',
        '/:.*magic_ore/',
        'gothic:wolfs_tooth',
        'gothic:old_mineshaft_pickaxe',
        'gothic:torturers_axe',
        'gothic:club',
        'gothic:mace',
        'gothic:urizel',




        //Beer Mod
        'drinkbeer:beer_mug',
        'drinkbeer:beer_mug_apple_lambic',
        'drinkbeer:beer_mug_blaze_stout',
        'drinkbeer:beer_mug_blaze_milk_stout',
        'drinkbeer:beer_mug_sweet_berry_kriek',
        'drinkbeer:beer_mug_haars_icey_pale_lager',
        'drinkbeer:beer_mug_pumpkin_kvass',
        'drinkbeer:beer_mug_night_howl_kvass',
        'drinkbeer:beer_mug_frothy_pink_eggnog',
        'drinkbeer:empty_beer_mug',



        //Dynamic Trees
        'dynamictrees:staff',

        //Medieval Craft

        //Valhelsia Structures
        'valhelsia_structures:stripped_lapidified_jungle_post',
        'valhelsia_structures:cut_stripped_lapidified_jungle_post',



        //Alex's Mobs
        'alexsmobs:ghostly_pickaxe',
        'alexsmobs:banner_pattern_bear',
        'alexsmobs:banner_pattern_australia_0',
        'alexsmobs:banner_pattern_australia_1',
        'alexsmobs:banner_pattern_new_mexico',
        'alexsmobs:banner_pattern_brazil',
        'alexsmobs:ancient_dart',
        'alexsmobs:dimensional_carver',
        'alexsmobs:shattered_dimensional_carver',

        // Potion Rings
        'potion_rings_rebooted:potion_ring_of_configuration',

        // Panthalassa
        'panthalassa:diving_suit_helmet',
        'panthalassa:diving_suit_chest',
        'panthalassa:diving_suit_legs',
        'panthalassa:diving_suit_boots',

        //Shields Plus

        'shieldsplus:netherite_shield',

        //Crayfish Gun Mod
        'cgm:stun_grenade',

        //Tetra
        'tetra:shootable_dummy',

        //The Abyss
        'theabyss:healing_camp_fire',
        'theabyss:shield_camp_fire',
        'theabyss:storyicon',
        //Ars Nouveau
        'ars_nouveau:temporary_block',



        //Artifacts
        "artifacts:flame_pendant",
        "artifacts:lucky_scarf",
        "artifacts:scarf_of_invisibility",
        "artifacts:shock_pendant",
        "artifacts:thorn_pendant",
        "artifacts:novelty_drinking_hat",
        "artifacts:plastic_drinking_hat",
        "artifacts:digging_claws",
        "artifacts:fire_gauntlet",
        "artifacts:pocket_piston",
        "artifacts:power_glove",
        "artifacts:vampiric_glove",
        "artifacts:bunny_hoppers",
        "artifacts:kitty_slippers",
        "artifacts:umbrella",
        "artifacts:aqua_dashers",
        "artifacts:whoopee_cushion",
        "artifacts:crystal_heart",
        "artifacts:obsidian_skull",
        "artifacts:helium_flamingo",
        "artifacts:golden_hook",
        "artifacts:snorkel",
        "artifacts:night_vision_goggles",
        "artifacts:everlasting_beef",
        "artifacts:eternal_steak",

        //kubejs
        'kubejs:cancelcraft',



        //Unusual End
        'unusualend:blob_shield',
        'unusualend:chorus_helmet',

        // Applied Energistics 2
        'ae2:facade',
        'ae2:fluix_pickaxe',
        'ae2:nether_quartz_pickaxe',
        'ae2:certus_quartz_pickaxe',
        'ae2:certus_quartz_axe',
        'ae2:certus_quartz_hoe',
        'ae2:certus_quartz_shovel',
        'ae2:certus_quartz_sword',
        'ae2:nether_quartz_axe',
        'ae2:nether_quartz_hoe',
        'ae2:nether_quartz_shovel',
        'ae2:nether_quartz_sword',
        'ae2:fluix_axe',
        'ae2:fluix_hoe',
        'ae2:fluix_shovel',
        'ae2:fluix_sword',

        //Minecolonies
        'minecolonies:spear',

        //Apotheosis
        'apotheosis:iron_mining_arrow',
        'apotheosis:diamond_mining_arrow',
        'apotheosis:potion_charm',
        'apotheosis:explosive_arrow',


        // Ars Nouveau
        'ars_nouveau:creative_spell_book',


        // Citadel
        'citadel:debug',
        'citadel:citadel_book',
        'citadel:effect_item',
        'citadel:fancy_item',

        // Create
        'create:copper_backtank_placeable',
        'create:potato_cannon',

        //Supplimentaries
        'supplementaries:slingshot',

        //quark
        'quark:charcoal_block',
        'quark:oak_chest',
        'quark:raw_iron_bricks',
        'quark:raw_gold_bricks',
        'quark:raw_copper_bricks',
        'quark:raw_iron_bricks_slab',
        'quark:raw_iron_bricks_stairs',
        'quark:raw_gold_bricks_slab',
        'quark:raw_gold_bricks_stairs',
        'quark:raw_copper_bricks_slab',
        'quark:raw_copper_bricks_stairs',
        'quark:raw_iron_bricks_vertical_slab',
        'quark:raw_gold_bricks_vertical_slab',
        'quark:raw_copper_bricks_vertical_slab',

        //Vertical Slabs
        '/:.*vertical_slab/',

        // Mekanism
        'mekanism:creative_fluid_tank',
        'mekanism:creative_chemical_tank',
        'mekanism:ingot_steel',
        'mekanism:personal_chest',
        'mekanism:personal_barrel',

        // Mekanism Additions
        'mekanismadditions:baby_creeper_spawn_egg',
        'mekanismadditions:baby_enderman_spawn_egg',
        'mekanismadditions:baby_wither_skeleton_spawn_egg',

        // Mekanism Tools
        /*'mekanismtools:lapis_lazuli_helmet',
        'mekanismtools:lapis_lazuli_chestplate',
        'mekanismtools:lapis_lazuli_leggings',
        'mekanismtools:lapis_lazuli_boots',
        'mekanismtools:lapis_lazuli_sword',
        'mekanismtools:lapis_lazuli_pickaxe',
        'mekanismtools:lapis_lazuli_axe',
        'mekanismtools:lapis_lazuli_shovel',
        'mekanismtools:lapis_lazuli_hoe',
        'mekanismtools:lapis_lazuli_paxel',
        'mekanismtools:lapis_lazuli_shield',
        'mekanismtools:steel_helmet',
        'mekanismtools:steel_chestplate',
        'mekanismtools:steel_leggings',
        'mekanismtools:steel_boots',
        'mekanismtools:bronze_pickaxe',
        'mekanismtools:bronze_axe',
        'mekanismtools:bronze_shovel',
        'mekanismtools:bronze_hoe',
        'mekanismtools:bronze_sword',
        'mekanismtools:bronze_paxel',
        'mekanismtools:bronze_helmet',
        'mekanismtools:bronze_chestplate',
        'mekanismtools:bronze_leggings',
        'mekanismtools:bronze_boots',
        'mekanismtools:bronze_shield',
        'mekanismtools:osmium_pickaxe',
        'mekanismtools:osmium_axe',
        'mekanismtools:osmium_shovel',
        'mekanismtools:osmium_hoe',
        'mekanismtools:osmium_sword',
        'mekanismtools:osmium_paxel',
        'mekanismtools:osmium_helmet',
        'mekanismtools:osmium_chestplate',
        'mekanismtools:osmium_leggings',
        'mekanismtools:osmium_boots',
        'mekanismtools:osmium_shield',
        'mekanismtools:refined_glowstone_pickaxe',
        'mekanismtools:refined_glowstone_axe',
        'mekanismtools:refined_glowstone_shovel',
        'mekanismtools:refined_glowstone_hoe',
        'mekanismtools:refined_glowstone_sword',
        'mekanismtools:refined_glowstone_paxel',
        'mekanismtools:refined_glowstone_helmet',
        'mekanismtools:refined_glowstone_chestplate',
        'mekanismtools:refined_glowstone_leggings',
        'mekanismtools:refined_glowstone_boots',
        'mekanismtools:refined_glowstone_shield', */

        // Quark
        'quark:carrot_crate',
        'quark:potato_crate',
        'quark:beetroot_crate',

        //YLF
        "ylf_mod:bird_cage",
        "ylf_mod:filledbirdcage",

        // Structure Gel API
        'structure_gel:red_gel',
        'structure_gel:blue_gel',
        'structure_gel:green_gel',
        'structure_gel:cyan_gel',
        'structure_gel:orange_gel',
        'structure_gel:yellow_gel',

        // Scaling health
        'scalinghealth:enchanted_heart',
        'scalinghealth:cursed_heart',
        'scalinghealth:chance_heart',

        //Forbidden Arcanus
        'forbidden_arcanus:deorum_helmet',
        'forbidden_arcanus:deorum_chestplate',
        'forbidden_arcanus:deorum_leggings',
        'forbidden_arcanus:deorum_boots',
        'forbidden_arcanus:reinforced_deorum_sword',
        'forbidden_arcanus:reinforced_deorum_shovel',
        'forbidden_arcanus:reinforced_deorum_pickaxe',
        'forbidden_arcanus:reinforced_deorum_axe',
        'forbidden_arcanus:reinforced_deorum_hoe',
        'forbidden_arcanus:edelwood_salmon_bucket',
        'forbidden_arcanus:boom_arrow',

        //Pneumaticcraft
        'pneumaticcraft:raw_salmon_tempura',
        'pneumaticcraft:salmon_tempura',
        'pneumaticcraft:cod_n_chips',

        //Epic Knights Mod
        'magistuarmory:face_helmet',
        'magistuarmory:lamellar_chestplate',
        'magistuarmory:lamellar_boots',
        'magistuarmory:chainmail_horse_armor',
        'magistuarmory:kastenbrust_boots',
        'magistuarmory:kastenbrust_leggings',
        'magistuarmory:kastenbrust_chestplate',
        'magistuarmory:grand_bascinet',
        'magistuarmory:cuirassier_boots',
        'magistuarmory:cuirassier_chestplate',
        'magistuarmory:cuirassier_helmet',
        'magistuarmory:wingedhussar_chestplate',
        'magistuarmory:xivcenturyknight_boots',
        'magistuarmory:xivcenturyknight_leggings',
        'magistuarmory:xivcenturyknight_chestplate',
        'magistuarmory:bascinet',
        'magistuarmory:rustedkettlehat',
        'magistuarmory:rustedchainmail_boots',
        'magistuarmory:rustedchainmail_leggings',
        'magistuarmory:rustedchainmail_chestplate',
        'magistuarmory:rustedchainmail_helmet',
        'magistuarmory:rustednorman_helmet',
        'magistuarmory:rustedcrusader_boots',
        'magistuarmory:rustedcrusader_chestplate',
        'magistuarmory:rustedgreathelm',
        'magistuarmory:rustedhalfarmor_chestplate',
        'magistuarmory:rustedbarbute',
        'magistuarmory:shishak',
        'magistuarmory:norman_helmet',
        'magistuarmory:brigandine_chestplate',
        'magistuarmory:gambeson_boots',
        'magistuarmory:pantyhose',
        'magistuarmory:gambeson_chestplate',
        'magistuarmory:coif',
        'magistuarmory:crusader_boots',
        'magistuarmory:crusader_leggings',
        'magistuarmory:greathelm',
        'magistuarmory:halfarmor_chestplate',
        'magistuarmory:barbute',
        'magistuarmory:gothic_boots',
        'magistuarmory:gothic_leggings',
        'magistuarmory:gothic_chestplate',
        'magistuarmory:sallet',
        'magistuarmory:jousting_boots',
        'magistuarmory:jousting_leggings',
        'magistuarmory:jousting_chestplate',
        'magistuarmory:stechhelm',
        'magistuarmory:armet',
        'magistuarmory:knight_chestplate',
        'magistuarmory:knight_leggings',
        'magistuarmory:knight_boots',
        'magistuarmory:copper_stylet',
        'magistuarmory:tin_stylet',
        'magistuarmory:bronze_stylet',
        'magistuarmory:copper_shortsword',
        'magistuarmory:tin_shortsword',
        'magistuarmory:bronze_shortsword',
        'magistuarmory:copper_katzbalger',
        'magistuarmory:tin_katzbalger',
        'magistuarmory:bronze_katzbalger',
        'magistuarmory:copper_pike',
        'magistuarmory:tin_pike',
        'magistuarmory:bronze_pike',
        'magistuarmory:copper_ranseur',
        'magistuarmory:tin_ranseur',
        'magistuarmory:bronze_ranseur',
        'magistuarmory:copper_ahlspiess',
        'magistuarmory:tin_ahlspiess',
        'magistuarmory:bronze_ahlspiess',
        'magistuarmory:copper_chivalrylance',
        'magistuarmory:tin_chivalrylance',
        'magistuarmory:bronze_chivalrylance',
        'magistuarmory:copper_bastardsword',
        'magistuarmory:tin_bastardsword',
        'magistuarmory:bronze_bastardsword',
        'magistuarmory:copper_estoc',
        'magistuarmory:tin_estoc',
        'magistuarmory:bronze_estoc',
        'magistuarmory:copper_claymore',
        'magistuarmory:tin_claymore',
        'magistuarmory:bronze_claymore',
        'magistuarmory:copper_zweihander',
        'magistuarmory:tin_zweihander',
        'magistuarmory:bronze_zweihander',
        'magistuarmory:copper_flamebladedsword',
        'magistuarmory:tin_flamebladedsword',
        'magistuarmory:bronze_flamebladedsword',
        'magistuarmory:copper_lochaberaxe',
        'magistuarmory:tin_lochaberaxe',
        'magistuarmory:bronze_lochaberaxe',
        'magistuarmory:copper_concavehalberd',
        'magistuarmory:tin_concavehalberd',
        'magistuarmory:bronze_concavehalberd',
        'magistuarmory:copper_heavymace',
        'magistuarmory:tin_heavymace',
        'magistuarmory:bronze_heavymace',
        'magistuarmory:copper_heavywarhammer',
        'magistuarmory:tin_heavywarhammer',
        'magistuarmory:bronze_heavywarhammer',
        'magistuarmory:copper_lucernhammer',
        'magistuarmory:tin_lucernhammer',
        'magistuarmory:bronze_lucernhammer',
        'magistuarmory:copper_morgenstern',
        'magistuarmory:tin_morgenstern',
        'magistuarmory:bronze_morgenstern',
        'magistuarmory:copper_chainmorgenstern',
        'magistuarmory:tin_chainmorgenstern',
        'magistuarmory:bronze_chainmorgenstern',
        'magistuarmory:copper_guisarme',
        'magistuarmory:tin_guisarme',
        'magistuarmory:bronze_guisarme',
        'magistuarmory:blacksmith_hammer',
        'magistuarmory:barbedclub',
        'magistuarmory:pitchfork',
        'magistuarmory:noble_sword',
        'magistuarmory:rusted_bastardsword',
        'magistuarmory:rusted_heavymace',
        'magistuarmory:club',
        'magistuarmory:wood_heatershield',
        'magistuarmory:stone_heatershield',
        'magistuarmory:iron_heatershield',
        'magistuarmory:gold_heatershield',
        'magistuarmory:diamond_heatershield',
        'magistuarmory:netherite_heatershield',
        'magistuarmory:copper_heatershield',
        'magistuarmory:steel_heatershield',
        'magistuarmory:silver_heatershield',
        'magistuarmory:tin_heatershield',
        'magistuarmory:bronze_heatershield',
        'magistuarmory:wood_target',
        'magistuarmory:stone_target',
        'magistuarmory:iron_target',
        'magistuarmory:gold_target',
        'magistuarmory:diamond_target',
        'magistuarmory:netherite_target',
        'magistuarmory:copper_target',
        'magistuarmory:steel_target',
        'magistuarmory:silver_target',
        'magistuarmory:tin_target',
        'magistuarmory:bronze_target',
        'magistuarmory:wood_buckler',
        'magistuarmory:stone_buckler',
        'magistuarmory:iron_buckler',
        'magistuarmory:gold_buckler',
        'magistuarmory:diamond_buckler',
        'magistuarmory:netherite_buckler',
        'magistuarmory:copper_buckler',
        'magistuarmory:steel_buckler',
        'magistuarmory:silver_buckler',
        'magistuarmory:tin_buckler',
        'magistuarmory:bronze_buckler',
        'magistuarmory:copper_rondache',
        'magistuarmory:tin_rondache',
        'magistuarmory:bronze_rondache',
        'magistuarmory:wood_tartsche',
        'magistuarmory:stone_tartsche',
        'magistuarmory:iron_tartsche',
        'magistuarmory:gold_tartsche',
        'magistuarmory:diamond_tartsche',
        'magistuarmory:netherite_tartsche',
        'magistuarmory:copper_tartsche',
        'magistuarmory:steel_tartsche',
        'magistuarmory:silver_tartsche',
        'magistuarmory:tin_tartsche',
        'magistuarmory:bronze_tartsche',
        'magistuarmory:wood_ellipticalshield',
        'magistuarmory:stone_ellipticalshield',
        'magistuarmory:iron_ellipticalshield',
        'magistuarmory:gold_ellipticalshield',
        'magistuarmory:diamond_ellipticalshield',
        'magistuarmory:netherite_ellipticalshield',
        'magistuarmory:copper_ellipticalshield',
        'magistuarmory:steel_ellipticalshield',
        'magistuarmory:silver_ellipticalshield',
        'magistuarmory:tin_ellipticalshield',
        'magistuarmory:bronze_ellipticalshield',
        'magistuarmory:stone_roundshield',
        'magistuarmory:iron_roundshield',
        'magistuarmory:gold_roundshield',
        'magistuarmory:diamond_roundshield',
        'magistuarmory:netherite_roundshield',
        'magistuarmory:copper_roundshield',
        'magistuarmory:steel_roundshield',
        'magistuarmory:silver_roundshield',
        'magistuarmory:tin_roundshield',
        'magistuarmory:bronze_roundshield',
        'magistuarmory:copper_pavese',
        'magistuarmory:tin_pavese',
        'magistuarmory:bronze_pavese',
        'magistuarmory:wood_kiteshield',
        'magistuarmory:stone_kiteshield',
        'magistuarmory:iron_kiteshield',
        'magistuarmory:gold_kiteshield',
        'magistuarmory:diamond_kiteshield',
        'magistuarmory:netherite_kiteshield',
        'magistuarmory:copper_kiteshield',
        'magistuarmory:steel_kiteshield',
        'magistuarmory:silver_kiteshield',
        'magistuarmory:tin_kiteshield',
        'magistuarmory:bronze_kiteshield',
        'magistuarmory:corruptedroundshield',
        'magistuarmory:apostolic_cross_pattern',
        'magistuarmory:bowl_pattern',
        'magistuarmory:bull_pattern',
        'magistuarmory:chess_pattern',
        'magistuarmory:crusader_cross_pattern',
        'magistuarmory:dragon_pattern',
        'magistuarmory:eagle_pattern',
        'magistuarmory:horse_pattern',
        'magistuarmory:lily_pattern',
        'magistuarmory:lion1_pattern',
        'magistuarmory:lion2_pattern',
        'magistuarmory:orthodox_cross_pattern',
        'magistuarmory:snake_pattern',
        'magistuarmory:sun_pattern',
        'magistuarmory:swords_pattern',
        'magistuarmory:tower_pattern',
        'magistuarmory:tree_pattern',
        'magistuarmory:two-headed_eagle_pattern',
        'magistuarmory:laceration',
        'magistuarmory:lamellar_rows',
        'magistuarmory:small_steel_plate',
        'magistuarmory:wood_chainmorgenstern',
        'magistuarmory:stone_chainmorgenstern',
        'magistuarmory:iron_chainmorgenstern',
        'magistuarmory:gold_chainmorgenstern',
        'magistuarmory:diamond_chainmorgenstern',
        'magistuarmory:netherite_chainmorgenstern',
        'magistuarmory:copper_chainmorgenstern',
        'magistuarmory:steel_chainmorgenstern',
        'magistuarmory:silver_chainmorgenstern',
        'magistuarmory:tin_chainmorgenstern',
        'magistuarmory:bronze_chainmorgenstern',
        'magistuarmory:steel_nugget',
        'magistuarmory:wood_bastardsword',
        'magistuarmory:stone_bastardsword',
        'magistuarmory:iron_bastardsword',
        'magistuarmory:gold_bastardsword',
        'magistuarmory:diamond_bastardsword',
        'magistuarmory:netherite_bastardsword',
        'magistuarmory:steel_bastardsword',
        'magistuarmory:silver_bastardsword',
        'magistuarmory:wood_katzbalger',
        'magistuarmory:stone_katzbalger',
        'magistuarmory:iron_katzbalger',
        'magistuarmory:gold_katzbalger',
        'magistuarmory:diamond_katzbalger',
        'magistuarmory:netherite_katzbalger',
        'magistuarmory:steel_katzbalger',
        'magistuarmory:silver_katzbalger',
        'magistuarmory:wood_claymore',
        'magistuarmory:stone_claymore',
        'magistuarmory:iron_claymore',
        'magistuarmory:gold_claymore',
        'magistuarmory:diamond_claymore',
        'magistuarmory:netherite_claymore',
        'magistuarmory:steel_claymore',
        'magistuarmory:silver_claymore',
        'magistuarmory:wood_heavymace',
        'magistuarmory:stone_heavymace',
        'magistuarmory:iron_heavymace',
        'magistuarmory:gold_heavymace',
        'magistuarmory:diamond_heavymace',
        'magistuarmory:netherite_heavymace',
        'magistuarmory:steel_heavymace',
        'magistuarmory:silver_heavymace',
        'magistuarmory:wood_morgenstern',
        'magistuarmory:stone_morgenstern',
        'magistuarmory:iron_morgenstern',
        'magistuarmory:gold_morgenstern',
        'magistuarmory:diamond_morgenstern',
        'magistuarmory:netherite_morgenstern',
        'magistuarmory:steel_morgenstern',
        'magistuarmory:silver_morgenstern',
        'magistuarmory:wood_guisarme',
        'magistuarmory:stone_guisarme',
        'magistuarmory:iron_guisarme',
        'magistuarmory:gold_guisarme',
        'magistuarmory:diamond_guisarme',
        'magistuarmory:netherite_guisarme',
        'magistuarmory:steel_guisarme',
        'magistuarmory:silver_guisarme',
        'magistuarmory:chainmail_helmet',
        'magistuarmory:chainmail_chestplate',
        'magistuarmory:chainmail_leggings',
        'magistuarmory:wood_rondache',
        'magistuarmory:chainmail_boots', //yes I just blacklisted over 300 weapons and armors! There were too many choices and most of them do the same things..breh >.>

        //Tan's Huge Trees
        'tht:d_1block',
        'tht:c_1block',
        'tht:b_1block',
        'tht:d_2block',
        'tht:a_1block',
        'tht:c_2block',
        'tht:c_3block',
        'tht:e_1block',
        'tht:e_4block',
        'tht:d_3block',
        'tht:d_4block',
        'tht:a_2block',
        'tht:a_3block',
        'tht:a_4block',
        'tht:a_5block',
        'tht:a_6block',
        'tht:a_7block',
        'tht:a_8block',
        'tht:a_9block',
        'tht:d_5block',
        'tht:e_5block',
        'tht:e_6block',
        'tht:e_7block',
        'tht:d_6block',
        'tht:d_7block',
        'tht:d_8block',
        'tht:c_4block',
        'tht:c_5block',
        'tht:d_9block',
        'tht:d_10block',
        'tht:b_2block',
        'tht:c_6block',
        'tht:d_11block',
        'tht:c_7block',
        'tht:e_8block',
        'tht:d_12block',
        'tht:c_8block',
        'tht:e_9block',
        'tht:e_10block',
        'tht:e_11block',
        'tht:e_12block',
        'tht:c_9block',
        'tht:c_10block',
        'tht:c_11block',
        'tht:d_13block',
        'tht:b_3block',
        'tht:b_4block',
        'tht:b_5block',
        'tht:b_6block',
        'tht:b_7block',
        'tht:b_8block',
        'tht:b_9block',
        'tht:b_10block',
        'tht:b_11block',
        'tht:b_12block',
        'tht:b_13block',
        'tht:b_14block',
        'tht:b_15block',
        'tht:c_12block',
        'tht:c_13block',
        'tht:c_14block',
        'tht:d_14block',
        'tht:d_15block',
        'tht:e_13block',
        'tht:e_14block',
        'tht:e_15block',
        'tht:e_3block',
        'tht:e_2block', //Lio will be proud of me I hope... *wipes sweat off face*

        //iter Rpg
        'iter_rpg:wooden_spear',
        'iter_rpg:magmanum_armor_helmet',
        'iter_rpg:magmanum_armor_chestplate',
        'iter_rpg:magmanum_armor_leggings',
        'iter_rpg:magmanum_armor_boots',
        'iter_rpg:magmanum_sword',
        'iter_rpg:magmanum_pickaxe',
        'iter_rpg:stone_spear',
        'iter_rpg:iron_spear',
        'iter_rpg:golden_spear',
        'iter_rpg:diamond_spear',
        'iter_rpg:netherite_spear',
        'iter_rpg:forest_spear',
        'iter_rpg:ocean_spear',
        'iter_rpg:sky_spear',
        'iter_rpg:hell_spear',
        'iter_rpg:wooden_flail',
        'iter_rpg:stone_flail',
        'iter_rpg:iron_flail',
        'iter_rpg:golden_flail',
        'iter_rpg:diamond_flail',
        'iter_rpg:netherite_flail',
        'iter_rpg:forest_flail',
        'iter_rpg:ocean_flail',
        'iter_rpg:sky_flail',
        'iter_rpg:hell_flail', //Again, too many weapons repeating the same things in Epic Knight's mod!

        //Alcocraft
        'alcocraftplus:keg',
        'alcocraftplus:mug_of_wither_stout',
        'alcocraftplus:mug_of_drowned_ale',
        'alcocraftplus:mug_of_ice_beer',
        'alcocraftplus:mug_of_kvass',

        //More Mekanism Processing //this is a small bi-product of whats happening in the craft tweaks' scripts>examples>mekanism folder
        'moremekanismprocessing:tungsten_ingot',
        'moremekanismprocessing:tungsten_nugget',
        'moremekanismprocessing:zinc_ingot',
        'moremekanismprocessing:zinc_nugget',
        'moremekanismprocessing:bismuth_ingot',
        'moremekanismprocessing:bismuth_nugget',
        'moremekanismprocessing:zinc_ingot',
        'moremekanismprocessing:zinc_nugget',
        'moremekanismprocessing:titanium_nugget',
        'moremekanismprocessing:titanium_ingot',
        'moremekanismprocessing:calorite_ingot',
        'moremekanismprocessing:calorite_nugget',
        'moremekanismprocessing:ostrum_ingot',
        'moremekanismprocessing:ostrum_nugget',
        'moremekanismprocessing:plainum_nugget',
        'moremekanismprocessing:platinum_ingot',
        'moremekanismprocessing:nickel_ingot',
        'moremekanismprocessing:nickel_nugget',
        'moremekanismprocessing:lithium_ingot',
        'moremekanismprocessing:lithium_nugget',
        'moremekanismprocessing:iridium_ingot',
        'moremekanismprocessing:iridium_nugget',
        'moremekanismprocessing:draconium_ingot',
        'moremekanismprocessing:draconium_nugget',
        'moremekanismprocessing:desh_ingot',
        'moremekanismprocessing:desh_nugget',
        'moremekanismprocessing:crimson_iron_ingot',
        'moremekanismprocessing:crimson_iron_nugget',
        '/:.*ostrum/',
        '/:.*titanium/',
        '/:.*calorite/',
        '/:.*iridium/',
        '/:.*draconium/',
        '/:.*desh/',
        '/:.*crimson_iron/',
        '/:.*desh/',
        '/:.*cobalt/',
        '/:.*azure_silver/',
        //Basic Nether Ores
        'bno:raw_zinc_block',
        'bno:raw_zinc',
        'bno:nether_nickel_ore',
        'bno:silver_ingot',
        'bno:silver_nugget',
        'bno:raw_nickel_block',
        'bno:nickel_block',
        'bno:raw_nickel',
        'bno:nickel_nugget',
        'bno:nickel_ingot',
        'bno:silver_ingot',
        'bno:tin_ingot',
        'bno:osmium_ingot',
        'bno:uranium_ingot',
        'bno:zinc_ingot',
        'bno:lead_nugget',
        'bno:silver_nugget',
        'bno:osmium_nugget',
        'bno:tin_nugget',
        'bno:zinc_nugget',
        'bno:raw_lead',
        'bno:raw_tin',
        'bno:raw_osmium',
        'bno:raw_uranium',
        'bno:uranium_block',
        'bno:zinc_block',
        'bno:raw_lead_block',
        'bno:raw_tin_block',
        'bno:raw_osmium_block',
        'bno:raw_uranium_block',
        'bno:lead_ingot',
        'bno:osmium_block',
        'bno:lead_block',
        'bno:copper_nugget',
        'bno:aluminum_nugget',
        'bno:aluminum_ingot',
        'bno:tin_block',

        // Stalwart Dungeons
        'stalwart_dungeons:chorundum_shield',
        'stalwart_dungeons:tungsten_shield',
        'stalwart_dungeons:warted_tungsten_shield',

        //Create
        'create:crushed_aluminum_ore',
        'create:crushed_nickel_ore',
        'create:netherite_backtank_placeable',

        //Upgrade Aquatic
        /*"upgrade_aquatic:bedroll",
        "upgrade_aquatic:white_bedroll",
        "upgrade_aquatic:orange_bedroll",
        "upgrade_aquatic:magenta_bedroll",
        "upgrade_aquatic:light_blue_bedroll",
        "upgrade_aquatic:yellow_bedroll",
        "upgrade_aquatic:lime_bedroll",
        "upgrade_aquatic:pink_bedroll",
        "upgrade_aquatic:gray_bedroll",
        "upgrade_aquatic:light_gray_bedroll",
        "upgrade_aquatic:cyan_bedroll",
        "upgrade_aquatic:purple_bedroll",
        "upgrade_aquatic:blue_bedroll",
        "upgrade_aquatic:brown_bedroll",
        "upgrade_aquatic:green_bedroll",
        "upgrade_aquatic:red_bedroll",
        "upgrade_aquatic:black_bedroll",*/
        //Enlightened End
        'enlightened_end:biome_replace_block',
        'enlightened_end:ebony_stalk_bulb',
        'enlightened_end:squelcher_spit',




        /*Just Enough Effects
        'upgrade_aquatic:vibing',
        'uprade_aquatic:restfulness',
        'uprade_aquatic:repellence',
        'uprade_aquatic:insomnia',
        'unusualend:ender_infection',
        'unusualend:buidling_inability',
        'enlightened_end:suffocation',
        'enlightened_end:radiated',
        'enlightened_end:oozed',
        'enlightened_end:burdened',
        'enlightened_end:bouncy',
        'better_katanas:suzumebachi_flower',
        -not working, rip Lio's JEI OCD 
        */

        //Better Katanas
        'better_katanas:suzumebachi', //way too super op |:<
        'better_katanas:suzumebachi_shikai', //way too super op |:<
        'better_katanas:sasuke_uchiha_spawn_egg',
        'better_katanas:heart_for_advancements',
        'better_katanas:yami_advita_slash',



        /* Bedrock Miner
        'bedrockminer:bedrock_boots',
        'bedrockminer:bedrock_leggings',
        'bedrockminer:bedrock_chestplate',
        'bedrockminer:bedrock_helmet',
        'bedrockminer:bedrock_hoe',
        'bedrockminer:bedrock_shovel',
        'bedrockminer:bedrock_axe',
        'bedrockminer:bedrock_sword',
        'bedrockminer:bedrock_pickaxe',*/

        //Tameable Beasts
        'tameablebeasts:iron_big_hoe',




    ])
})


REIEvents.hide('item', e => {
    e.hide('@medieval_craft_structures')
    e.hide('@medieval_craft_weapons')
    e.hide('@weirdmobs')
})