// priority: 1
ClientEvents.lang('en_us', event => {
  const rename = (item, newName) => event.add(Item.of(item).item.getDescriptionId(), newName)
    rename("minecraft:large_fern", '§aTall Fern')
    rename("minecraft:tall_grass", '§aOvergrown Grass')
    rename("minecraft:tropical_fish", 'Exotic Fish')
    rename("minecraft:tropical_fish_bucket", 'Bucket of Exotic Fish')
    rename("forbidden_arcanus:edelwood_tropical_fish_bucket", '§9Edelwood Bucket of Exotic Fish')
    rename("minecraft:cod", 'River Fish')
    rename("minecraft:salmon", 'Ocean Fish')
    rename("minecraft:cooked_salmon", 'Cooked Ocean Fish')
    rename("minecraft:salmon_bucket", 'Bucket of Ocean Fish')
    rename("minecraft:cod_spawn_egg", 'River Fish Spawn Egg')
    rename("minecraft:cod_bucket", 'Bucket of River Fish')
    rename("minecraft:mushroom_stew", '§7Mushroom Soup')
    rename("aquaculture:turtle_soup", '§7Turtle Soup')
    rename("forbidden_arcanus:bat_soup", '§7Bat Soup')
    rename("minecraft:beetroot_soup", '§7Beetroot Soup')
    rename("minecraft:cooked_cod", 'Cooked River Fish')
    rename("forbidden_arcanus:edelwood_cod_bucket", '§9Edelwood Bucket of River Fish')
    rename("minecraft:rabbit_stew", '§7Rabbit Soup')
    rename("minecraft:oak_leaves", '§2Oak Foliage')
    rename("minecraft:spruce_leaves", '§2Spruce Foliage')
    rename("minecraft:birch_leaves", '§2Birch Foliage')
    rename("minecraft:jungle_leaves", '§2Jungle Foliage')
    rename("minecraft:acacia_leaves", '§2Acacia Foliage')
    rename("minecraft:dark_oak_leaves", '§2Dark Oak Foliage')
    rename("minecraft:mangrove_leaves", '§2Mangrove Foliage')
    rename("minecraft:azalea_leaves", '§2Azalea Foliage')
    rename("minecraft:flowering_azalea_leaves", '§2Flowering Azalea Foliage')
    rename("upgrade_aquatic:river_leaves", '§2River Foliage')
    rename("minecraft:cobweb", '§fSticky Web')
    rename("forbidden_arcanus:cherry_leaves", '§2Cherry Foliage')
    rename("forbidden_arcanus:aurum_leaves", '§2Aurum Foliage')
    rename("forbidden_arcanus:nuggety_aurum_leaves", '§2Nuggety Aurum Foliage')
    rename("quark:blue_blossom_leaves", '§2Blue Blossom Foliage')
    rename("quark:lavender_blossom_leaves", '§2Lavender Blossom Foliage')
    rename("quark:orange_blossom_leaves", '§2Orange Blossom Foliage')
    rename("quark:pink_blossom_leaves", '§2Pink Blossom Foliage')
    rename("quark:yellow_blossom_leaves", '§2Yellow Blossom Foliage')
    rename("quark:red_blossom_leaves", '§2Red Blossom Foliage')
    rename("quark:ancient_leaves", '§2Ancient Blossom Foliage')
    rename("theabyss:blaru_leaves", '§2Blaru Foliage')
    rename("theabyss:jungle_leaves", '§2Abyssal Jungle Foliage')
    rename("theabyss:frozen_leaves", '§2Frozen Foliage')
    rename("theabyss:bog_shroom_leave", '§2Bog Shroom Foliage')
    rename("theabyss:blaru_leave_carpet", '§2Blaru Leaf Carpet')
    rename("theabyss:jungle_leave_carpet", '§2Jungle Leaf Carpet')
    rename("theabyss:vigilant_leaves", '§2Vigilant Foliage')
    rename("ars_nouveau:blue_archwood_leaves", '§2Blue Archwood Foliage')
    rename("ars_nouveau:purple_archwood_leaves", '§2Purple Archwood Foliage')
    rename("ars_nouveau:green_archwood_leaves", '§2Green Archwood Foliage')
    rename("ars_nouveau:red_archwood_leaves", '§2Red Archwood Foliage')
    rename("iter_rpg:sacred_leaves", '§6Scared Foliage')
    rename("hexfortress:wither_leaves", '§0Withered Foliage')
    rename("minecraft:campfire", '§eCampfire')
    rename("hexfortress:blaze_key", '§6Fiery Key')
    rename("castle_in_the_sky:red_key", '§4Key of Might')
    rename("castle_in_the_sky:blue_key", '§9Key of Knowledge')
    rename("castle_in_the_sky:yellow_key", '§eKey of Light')
    rename("castle_in_the_sky:red_door", '§4Door of Might')
    rename("castle_in_the_sky:blue_door", '§9Door of Knowledge')
    rename("castle_in_the_sky:yellow_door", '§eDoor of Light')
    rename("tombstone:grave_key", '§6Skeleton Key')
    rename("minecraft:diamond", '§bDiamond')
    rename("minecraft:emerald", '§aEmerald')
    rename("minecraft:lapis_lazuli", '§9Lapis Lazuli')
    rename("minecraft:amethyst_shard", '§dAmethyst Shard')
    rename("minecraft:raw_iron", '§8Unrefined Iron')
    rename("minecraft:raw_gold", '§6Unrefined Gold')
    rename("minecraft:raw_copper", '§8Unrefined Copper')
    rename("create:raw_zinc", '§eUnrefined Zinc')
    rename("create:crushed_raw_iron", '§8Crushed Iron')
    rename("create:crushed_raw_gold", '§6Crushed Gold')
    rename("create:crushed_raw_copper", '§8Crushed Copper')
    rename("create:crushed_raw_zinc", '§eCrushed Zinc')
    rename("create:crushed_raw_osmium", '§8Crushed Osmium')
    rename("create:crushed_raw_silver", '§7Crushed Silver')
    rename("create:crushed_raw_tin", '§8Crushed Tin')
    rename("create:crushed_raw_lead", '§8Crushed Lead')
    rename("create:crushed_raw_aluminum", '§8Crushed Aluminum')
    rename("create:crushed_raw_uranium", '§aCrushed Uranium')
    rename("create:crushed_raw_nickel", '§8Crushed Nickel')
    rename("mekanism:raw_osmium", '§8Unrefined Osmium')
    rename("mekanism:raw_tin", '§8Unrefined Tin')
    rename("mekanism:raw_lead", '§8Unrefined Lead')
    rename("mekanism:raw_uranium", '§aUnrefined Uranium')
    rename("bno:raw_aluminum", '§8Unrefined Aluminum')
    rename("bno:raw_silver", '§7Unrefined Silver')
    rename("stalwart_dungeons:raw_tungsten", '§aUnrefined Tungsten')
    rename("enlightened_end:raw_bismuth", '§5Unrefined Bismuth')
    rename("ylf_mod:brokenice", '§bBroken Ice')
    rename("minecraft:raw_iron_block", '§8Unrefined Iron Block')
    rename("minecraft:raw_gold_block", '§6Unrefined Gold Block')
    rename("minecraft:raw_copper_block", '§8Unrefined Copper Block')
    rename("create:raw_zinc_block", '§eUnrefined Zinc Block')
    rename("mekanism:block_raw_osmium", '§8Unrefined Osmium Block')
    rename("mekanism:block_raw_tin", '§8Unrefined Tin Block')
    rename("mekanism:block_raw_lead", '§8Unrefined Lead Block')
    rename("mekanism:block_raw_uranium", '§aUnrefined Uranium Block')
    rename("bno:raw_aluminum_block", '§8Unrefined Aluminum Block')
    rename("bno:raw_silver_block", '§7Unrefined Silver Block')
    rename("enlightened_end:raw_bismuth_block", '§5Unrefined Bismuth Block')
    rename("alcocraftplus:mug_of_nether_star_lager", '§9Mead of Flight')
    rename("alcocraftplus:mug_of_chorus_ale", '§9§l§oBitter Mead of Flight')
    //Ingredient.of(/:.*vertical/).stacks.forEach(item => rename(item, '§7'+ item.item.getName(item).string))
    //Ingredient.of(/:.*framed/).stacks.forEach(item => rename(item, '§7'+ item.item.getName(item).string))
    
    //Ingredient.of(/:.*trapdoor/).stacks.forEach(item => rename(item, '§7'+ item.item.getName(item).string))
    //Ingredient.of(/:.*compat/).stacks.forEach(item => rename(item, '§7'+ item.item.getName(item).string))
    /*Ingredient.of(/:.*diamond/).stacks.forEach(item => rename(item, '§b'+ item.item.getName(item).string))
    Ingredient.of(/:.*gold/).stacks.forEach(item => rename(item, '§6'+ item.item.getName(item).string))
    Ingredient.of(/:.*emerald/).stacks.forEach(item => rename(item, '§a'+ item.item.getName(item).string))
    Ingredient.of(/:.*netherite/).stacks.forEach(item => rename(item, '§d'+ item.item.getName(item).string))
    */
    //Ingredient.of(/:.*plank/).stacks.forEach(item => rename(item, '§9'+ item.item.getName(item).string))
  })
 